<?php
/**
 * Attributes File.
 *
 * @since 1.2.0
 *
 * @package spectra-pro
 */
$cat_border_attribute = UAGB_Block_Helper::uag_generate_border_attribute( 'cat' );

return array_merge(
	array(
		'catAlign'               => 'left',
		'catAlignTablet'         => '',
		'catAlignMobile'         => '',
		'catWidth'               => 50,
		'catWidthTablet'         => '',
		'catWidthMobile'         => '',
		'catWidthUnit'           => '%',
		'catWidthUnitTablet'     => '%',
		'catWidthUnitMobile'     => '%',
		'catBorderHColor'        => '',
		'paddingCatTop'          => 8,
		'paddingCatRight'        => 12,
		'paddingCatBottom'       => 8,
		'paddingCatLeft'         => 12,
		'paddingCatTopTablet'    => '',
		'paddingCatRightTablet'  => '',
		'paddingCatBottomTablet' => '',
		'paddingCatLeftTablet'   => '',
		'paddingCatTopMobile'    => '',
		'paddingCatRightMobile'  => '',
		'paddingCatBottomMobile' => '',
		'paddingCatLeftMobile'   => '',
		'paddingCatUnit'         => 'px',
		'paddingCatUnitMobile'   => 'px',
		'paddingCatUnitTablet'   => 'px',
		'catTextColor'           => '',
		'catFieldColor'          => '',
		'catFontFamily'          => 'Default',
		'catFontWeight'          => '',
		'catFontSize'            => 15,
		'catFontSizeType'        => 'px',
		'catFontSizeTypeTablet'  => 'px',
		'catFontSizeTypeMobile'  => 'px',
		'catFontSizeTablet'      => 15,
		'catFontSizeMobile'      => 15,
		'catLineHeight'          => '',
		'catLineHeightType'      => 'em',
		'catLineHeightTablet'    => '',
		'catLineHeightMobile'    => '',
		'catloadGoogleFonts'     => false,
		'catLetterSpacing'       => '',
		'catLetterSpacingTablet' => '',
		'catLetterSpacingMobile' => '',
		'catLetterSpacingType'   => 'px',
		'marginCatTop'           => 12,
		'marginCatRight'         => 12,
		'marginCatBottom'        => 12,
		'marginCatLeft'          => 12,
		'marginCatTopTablet'     => '',
		'marginCatRightTablet'   => '',
		'marginCatBottomTablet'  => '',
		'marginCatLeftTablet'    => '',
		'marginCatTopMobile'     => '',
		'marginCatRightMobile'   => '',
		'marginCatBottomMobile'  => '',
		'marginCatLeftMobile'    => '',
		'marginCatUnit'          => 'px',
		'marginCatUnitMobile'    => 'px',
		'marginCatUnitTablet'    => 'px',
		'rowGapDesktop'          => 10,
		'rowGapTablet'           => '',
		'rowGapMobile'           => '',
		'rowGapType'             => 'px',
		'rowGapTypeTablet'       => 'px',
		'rowGapTypeMobile'       => 'px',
		'columnGapDesktop'       => 10,
		'columnGapTablet'        => '',
		'columnGapMobile'        => '',
		'columnGapType'          => 'px',
		'columnGapTypeTablet'    => 'px',
		'columnGapTypeMobile'    => 'px',
		'betweenGapDesktop'      => 10,
		'betweenGapTablet'       => '',
		'betweenGapMobile'       => '',
		'betweenGapType'         => 'px',
		'betweenGapTypeTablet'   => 'px',
		'betweenGapTypeMobile'   => 'px',
		'layout'                 => 'stack',
		'layoutTablet'           => 'stack',
		'layoutMobile'           => 'stack',
		'catTransform'           => 'none',
	),
	$cat_border_attribute
);
